<?php

echo $this->pageTitle($this->translate('Oai-Pmh Please choose sets to import'), 1, $this->translate('Oai-Pmh Harvester')); 

echo $content;

echo $this->form()->openTag($form); 
?>
<fieldset id='page-actions'>
    <button type="submit"><?php echo $this->translate('Harvest'); ?></button>
</fieldset>

<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag($form); ?>